### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by fjook** [egara/arch-btrfs-installation#2]
Hi! Thanks for the awesome guide. I just followed and installed Arch with btrfs on my laptop.

If you don't mind, I have a question regarding `docker`. I use `docker` and `docker-compose`, both on my work laptop and server. I don't use Arch on server but Ubuntu.

I believe this [section](https://github.com/egara/arch-btrfs-installation#problem-with-docker-and-btrfs) is more likely for the Arch servers, right? Or, I should do it whether it is server or not?

---

By the way, did you mean `mkdir /mnt/defvol` instead of `mkdir /mnt/mnt/defvol`?

**Comment by egara** [comment]
Hi @fjook and thank you very much for your kind words. I'm very glad that you find this guide useful :)

Let's see your questions:

> I use docker and docker-compose, both on my work laptop and server. I don't use Arch on server but Ubuntu. I believe this section is more likely for the Arch servers, right? Or, I should do it whether it is server or not?

No, this is not only an Arch thing. And this is not a really problem but you need to be careful. When you choose BTRFS as your filesystem and install Docker, you will see that the [storage driver](https://docs.docker.com/storage/storagedriver/select-storage-driver/) selected by default is BTRFS (type **docker info** in your terminal to see the storage driver configured by Docker). 
The thing is that when you create a new container with **docker run** or **docker-compose**, because storage driver is BTRFS, Docker will create subvolumes within /var/lib/docker/btrfs/subvolumes. Those subvolumes will be created directly from the subvolume mounted as root (**rootvol** in the guide).

What happens then? Ok, if you create a snapshot of **rootvol**, BTRFS will not include subvolumes inside this subvolume, so all the subvolumes (sorry for all the subvolumes words lol) created by Docker won't be included in the snapshot.

Whan can you do? At this point, I can think of two possible solutions:

- Create a specific BTRFS subvolume at level 5 for **/var/lib/docker/btrfs/subvolumes**, i.e., go to /mnt/defvol which is the whole BTRFS volume (following the guide) and create, at this level, another subvolume. Then add a new line in **/etc/fstab** to mount it in **/var/lib/docker/btrfs/subvolumes** when the system boots.

- Change the Docker storage Driver as I suggest in the guide in order to avoid this problem. By the way, I have just seen that **devicemapper** driver will be deprecated and now it is better to choose **overlay2**


> By the way, did you mean mkdir /mnt/defvol instead of mkdir /mnt/mnt/defvol?

No, this is not a typo. Remember that you are mounting your filesystem on /mnt in order to do the installation of Arch Linux, so /mnt will be your "root" partition when you chroot in it for the installation process.

I hope this help you!! And thanks again for your kind words!!

**Comment by fjook** [comment]
Thank you so much, I learned quite a lot from you. :) Stay safe and have a good day!

**Comment by egara** [comment]
Same for you and thanks!!
