### ISSUE TITLE
Why a subvolume for /tmp?

### ISSUE THREAD

**Issue by simonwiles** [egara/arch-btrfs-installation#5]
Is there any advantage of having `/tmp` as a separate btrfs subvolume over just mounting a `tmpfs` device at that location?  Are there circumstances under which `/tmp` would ever be just a regular directory on the root fs?  Thanks!

**Comment by egara** [comment]
Hi @simonwiles and thank you very much for your feedback and comments.

Some months ago I received an e-mail of an Arch user that told me the exact same thing. I think when I installed Arch Linux in my laptop for the first time and started to write this cheatsheet Arch didn't use **tmpfs** device for **/tmp**.

I didn't want to include all the files within **/tmp** every time I created a snapshot, so I though the best idea was to create another subvolume for **/tmp**.

Then, at some point, Arch introduced this way to deal with temporal files and I remember I started to have problems, because those files weren't removed between reboots. That's why I wrote [this solution in the cheatsheet](https://github.com/egara/arch-btrfs-installation#tmp-folder). The user who wrote me the e-mail told me that **tmpfs** avoided to include the files within the BTRFS snapshots, but I haven't tested it yet. So if it is working fine, then there's no need to create a new subvolume for **/tmpfs** anymore and I should upgrade this guide too.

Could you tell me your experience with **tmpfs** and the way it behaves?

Thanks for sharing it!

**Comment by simonwiles** [comment]
Thanks @egara -- yes, my experience is that new installs default to mounting `/tmp` as a `tmpfs` devices (and that's been the case for long while, as far as I'm aware), and that the contents are not included in snapshots made of the root `/` subvolume.  So, as far as I can see, there's no value in making a separate BTRFS subvolume for `/tmp`, if the purpose is to exclude the contents from snapshots.

I also think your "Problem with Docker and BTRFS" section might need an update, too.  Docker defaults to using the `overlay2` storage driver, rather than a BTRFS subvolume, so there's no problem with snapshots unless you specifically ask docker to use a subvolume (in which case you presumably have a plan).

Thanks for your document -- it has been a useful read :)

**Comment by egara** [comment]
Thank you very much for your comments @simonwiles 

It is great this kind of feedback because this cheatsheet is intended to be upgraded and up to date in order to help other users to install Arch using BTRFS.

So I have to update it with your comments as soon as I can.

Again, thank you very much :D

**Comment by egara** [comment]
I have modified the document according to your comments about /tmp.

Thanks for contributing!
