### ISSUE TITLE
Replacing grub with systemd-boot?

### ISSUE THREAD

**Issue by ghost** [egara/arch-btrfs-installation#8]
Thanks for the amazing project, this will always be my go-to for archlinux installation...
Just wanted to ask whether is it possible to install **system-boot** to /boot/efi instead of **grub**?
Thanks in advance :) .

**Comment by egara** [comment]
Hi, and thank you for your kind words.

Yes, of course, you can implement systemd-boot instead of traditional grub but you have to take into account one important thing. Using grub, you will be able to populate all your root snapshots, so when grub starts and you see the inital boot screen, you will be able to choose the exact snapshot you want to boot in. This is great if you want to rollback if, let's say, an update has messed up your system.

I think with systemd-boot you won't be able to have this great feature. I hope it helps. Thanks again!

**Comment by Llamach** [comment]
It's a bit tricky to set up systemd boot in a partition like this so I guess I'll continue using grub 😅.
Sorry for my ignorance but what does hash in upgrade-system.sh mean?
Thanks
