### ISSUE TITLE
Systemd-boot installation?

### ISSUE THREAD

**Issue by ghost** [egara/arch-btrfs-installation#9]
Previously I created a thread asking if systemdboot was compatible with this installation.
I tried installing the boot with `bootctl --esp-path=/boot/efi` it went successfully then I copied `arch-btrfs.conf` from the repo but it didn't work out.
`/boot/efi/loader/entries/arch-btrfs.conf`
Is the location of the entry.
Any advices?
Thanks in advance.
EDIT: systemd-boot requires a *fat32* partition for installation. So if `/dev/sda1` is mounted as `/boot` I guess it won't get snapshot. Also if `/dev/sda1` is mounted as `/boot/efi` systemd boot config does not read the vmlinux-linux and .img in `/boot`. Are there any possible solutions to solve both of these issues?
Again thanks

**Comment by egara** [comment]
Hi @Llamach 

This guide has been changing from time to time because I detected some problems and I have tried to polish it with every version. First, the guide was written using systemd-boot instead of GRUB. You [can see here the last version of the guide with this type of booting system instead of  GRUB](https://github.com/egara/arch-btrfs-installation/tree/3b3d8e14e686827dd7ee6812821fa42b9ad1adb9). In this version, you can see all the steps I did to implement systemd-boot. 

But, as I told you in the other issue you created, systemd-boot was replaced by GRUB in this guide because there is a tool called grub-btrfs which detects and includes btrfs snapshots in GRUB boot options, so you can select the specific snapshot you want to boot. This is great if your current root partition doesn't boot because of a system update. I would encourage you to change your booting manager because of this feature, which is HUGE in my humble opinion.

And you are right. If you have mounted /boot partition directly, this partition won't be included in the root snapshots, which is very bad if you want to rollback your system and the version of your kernel has been upgraded for example. That's why in my recent guide the partition I use for EFI is mounted at /boot/efi, so /boot will be snapshoted and EFI won't need to be backed up.

Again, in order to avoid all of these problems you have detected as well, I would encourage you to change systemd-boot to GRUB and use /boot/efi as mounted point.

I hope this helps!

**Comment by ghost** [comment]
I am sorry I didn't notice that guide.
I think I'll switch over to grub because grub-btrfs is indeed a very useful tool.
Thanks for the reply.
Have a great day :)
